# Generated by Django 4.0.6 on 2022-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='User123', max_length=128),
            preserve_default=False,
        ),
    ]
